name: GitHub Pages - MdBook Deployment

on:
  push:
    paths:
      - 'tutorial/**'

defaults:
  run:
    working-directory: ./tutorial

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build dependencies
        run: cargo build

      - uses: peaceiris/actions-mdbook@v1
        with:
            mdbook-version: '0.4.8'
            # mdbook-version: 'latest'

      - name: Check mdBook
        run: mdbook test -L ./target/debug/deps

      - name: Build mdBook
        run: mdbook build ./tutorial

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book